apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: metallb-helm-chart-value-overrides
    namespace: metallb-system
    files:
      - values.yaml
resources:
  - metallb.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: sre-team
