apiVersion: v1
kind: Namespace
metadata:
  name: reloader

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stakater-reloader
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.2.5
      sourceRef:
        kind: HelmRepository
        name: stakater-reloader
        namespace: reloader
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: reloader-values
      valuesKey: values.yaml
