apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: default
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: vaultwarden-values
    - kind: Secret
      name: admin-password
      targetPath: env.ADMIN_TOKEN
      valuesKey: admin_password
