apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: tailscale-values
    namespace: tailscale
    files:
      - values.yaml
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - oauth-secret.yaml
