apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  chart:
    spec:
      chart: zigbee2mqtt
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: andrenarchy
        namespace: zigbee2mqtt
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: zigbee2mqtt-values
