apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: postgres-values
    namespace: postgres
    files:
      - values.yaml
