---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  interval: 60m0s
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values
