apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: keda-values
    namespace: keda
    files:
      - values.yaml
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
