apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 30m
  chart:
    spec:
      chart: keda
      version: "2.13.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: keda-values
      valuesKey: values.yaml
