apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: webhook-values
    namespace: cert-manager
    files:
      - values.yaml
resources:
  - repository.yaml
  - release.yaml
