apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/shared-repositories
  - ../base/dynamic-dns
  - ../base/external-dns
  - ../base/pihole
  - ../base/paperless
  - ../base/jellyfin
  - ./paperless.yaml
  - ../base/home-assistant
  - ../base/audiobookshelf
  - ../base/calibre-web
  - ../base/castsponsorskip
  - ../base/vaultwarden
  - ../base/woodpecker-ci
  - ../base/kanidm
  - ../base/ntfy
  - ../base/immich
patchesStrategicMerge:
  - pihole-values.yaml

configurations:
  - kustomizeconfig.yaml
