apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/shared-repositories
  - ../base/external-dns
  - ../base/pihole
patchesStrategicMerge:
  - pihole-values.yaml
configurations:
  - kustomizeconfig.yaml
