apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/shared-repositories
  - ../base/dynamic-dns
  - ../base/external-dns
  - ../base/pihole
  - ../base/paperless
  - ../base/homer
  - ../base/jellyfin
  - ./paperless.yaml
  - ../base/home-assistant
  - ../base/audiobookshelf
  - ../base/calibre-web
  - ../base/ihatemoney
  - ../base/vaultwarden
  - ../base/woodpecker-ci
  - ../base/kanidm
patchesStrategicMerge:
  - pihole-values.yaml
configurations:
  - kustomizeconfig.yaml
