nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
      - path: spec/template/volumes/configMap/name
        kind: StatefulSet
  - kind: Secret
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
      - path: spec/template/volumes/secret/secretName
        kind: StatefulSet
