apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  values:
    serviceDns:
      loadBalancerIP: "10.1.11.2"
    virtualHost: pihole.x86.thephysicsflat.xyz
    ingress:
      tls:
        - secretName: pihole-tls
          hosts:
            - pihole.x86.thephysicsflat.xyz
      hosts:
        - pihole.x86.thephysicsflat.xyz
