---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-books
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs.home.thephysicsflat.xyz
    path: "/srv/books/Books"
    readOnly: true
  mountOptions:
    - nfsvers=3
    - nolock
    - soft
    - timeo=600
    - retrans=3
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-books
  namespace: calibre-web
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 64Gi
  volumeName: calibre-web-books
