apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  chart:
    spec:
      chart: ntfy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: default
  interval: 60m0s
  valuesFrom:
    - kind: ConfigMap
      name: ntfy-values
