apiVersion: v1
kind: Secret
metadata:
    name: ntfy-data
    namespace: ntfy
type: Opaque
stringData:
    NTFY_SMTP_SENDER_USER: ENC[AES256_GCM,data:zuzrFgulRFsU2irLUYhJf95KqPXWZKnl,iv:xYt0UhCFIScCKbeEA0ye6qQ1m75osC489gWo+3xZpbE=,tag:gWUyfXkSZ/4G5DT9MEzG2w==,type:str]
    NTFY_SMTP_SENDER_FROM: ENC[AES256_GCM,data:P5lifL9m2RpsgHeE4y6LsekYhoaJhVGs,iv:C1mWS707tDPe3My1h/loAnev+w/GiFCDlXBRsnNkuHE=,tag:gYfri7bgMn4SiFNU/e22LQ==,type:str]
data:
    NTFY_WEB_PUSH_PRIVATE_KEY: ENC[AES256_GCM,data:KYfNUGP54FVy5a2TSOP4AoVsibLnn7w0H+jB47zuI9VG2TNvLpawWqHMFeUyK/+Yk0l0yXTEkQdBJsPV,iv:fFYG6m9l/GyiAUcH+n+qR7g3Eoy9ceWesiKpvwELWk0=,tag:jqJoxcjB/rAjVC8y8e53Tg==,type:str]
    NTFY_SMTP_SENDER_PASS: ENC[AES256_GCM,data:FGpbbDNKx5mtGf7wajWamQ==,iv:wfxsXjjDglcWRfnM9JN8GF6tbUmB87wFMCioWNnBqhA=,tag:dIBwHuNChD8pDv+sSU+Q3A==,type:str]
sops:
    age:
        - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzRoNGJQVkxZZHZjbmhl
            UVF6TytMeldpRklsaDVMYXdhYXdRMTZLK1ZNCmRTNVVHVnJIRUprUEd4L2JsZ3RP
            U1ozZmh5eU1QeDdOSUhXOHJhSlBUbGsKLS0tIHJJUHdVdGQrZFRsT01YMzJPQ3hp
            dGRaWDRDSCswUHZxZ2ZqRlNjaU9pY1kKMGDtq+6OeSZZJPwFt36wW9Kw9gUQjnoA
            Js4TzjUeIyAp9ZL5qZsbReGQfe+5huZwTOXDVewAEnG0CuW0shdVBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T15:00:18Z"
    mac: ENC[AES256_GCM,data:zgrqlqEUAncFuudY5+nWTwsCKv+vkX3Bf6Fq11+fng/aDj6Q0ot5aOSKCBc1k+ELrAiVlCIZ8e7CTYso7Uxon2xsXMYqvplu1DpkAjP4BlhMcZiOvlh1qWC+UeeJeYapVn05zgfs6RrksJAPxTDQz5YG7gaNGhjhkPHV/pKoj54=,iv:gF7IXoPajPdIyWur1mBzh9hyd5g1Yrf0R3COVTKhutU=,tag:aDmil/bK7rRm3bIQ/9dKOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
