apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: woodpecker-ci
  namespace: woodpecker
spec:
  releaseName: woodpecker
  chart:
    spec:
      chart: woodpecker
      reconcileStrategy: ChartVersion
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: woodpecker
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: woodpecker-values
  upgrade:
    force: true
    crds: CreateReplace
