apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: woodpecker-secret
    namespace: woodpecker
data:
    WOODPECKER_GITEA_CLIENT: ENC[AES256_GCM,data:/wuZtWagl9c/418Y93SpkSxI4AwrftD9+CEqBSyhdC/toggS,iv:CfT+XOxfn3+/jBMrdFJyfqECeFR3Lk9Txxhcr9rarGs=,tag:5dSivfV5VLMLG9ThiN2Rkw==,type:str]
    WOODPECKER_GITEA_SECRET: ENC[AES256_GCM,data:JxJw2BPgcePHBcLJauZSxbTA63L4RW3UsdcLywUNRy+mLSpjCXk6pgk3E94Qrx51R+e3zRC0H4o=,iv:1KY7RQtYvlEOKvtPCDPaJWr858VVbDoGjVXiySVGNqU=,tag:DMzcCwgMia3IS5j8UFKqEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUC9tekxQZjhPVkNsNG93
            UGxUM29wZURRQmdPZ2h4RzVROCt5bUNKQVJNCjJFVHlKZ1djSzJDR3RHRmY0Y0Nm
            VTZvazVVZDNFNnJGVjFSV1U1ZStaVjQKLS0tIDF5WjIvZVpHZmVORGJEWVhTbzhD
            c0tMbzBiN2ZQT1E1NjlkNVBZdmlJWE0K0B3kpfpnUnaJPpwmpCkFoYlwg5WRB8T7
            4lJIJmHwZQt4fpchDWRPMKMqoWw80xyzhxCPKaIlwokdLwc7TVvu+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T17:44:48Z"
    mac: ENC[AES256_GCM,data:i3n92QT34EzJv+FWjQbOjbWSxj8ak3WOqTlfAJlf0cjs/1a7zznVMS0tkTCm73lrjyez+xXyv+K18r91T9EJcAKkgi+hSWT4+20ZlBUa6SNT2gixUhvVfKgAIasTmFFPk47wqdsqdw2ztcU4/fTqq1xz44F87g3dkB0s+KO//Kk=,iv:uN3SZddXstqbAzK3QXnRze3PV0m38cZOQPKCTn0ZyS0=,tag:r93sz8GN4OhKyt2XO6yfKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
