---
apiVersion: v1
kind: Namespace
metadata:
  name: generic-device-labeller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm
  namespace: generic-device-labeller
spec:
  interval: 24h
  url: https://charts.gabe565.com
