apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: generic-device-values
    namespace: generic-device-labeller
    files:
      - values.yaml
      - "plugin-config.yaml"
resources:
  - helm-repo.yaml
  - release.yaml
