apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: generic-device-labeller
  namespace: generic-device-labeller
spec:
  interval: 30m
  chart:
    spec:
      chart: generic-device-plugin
      version: "0.1.3"
      sourceRef:
        kind: HelmRepository
        name: helm
        namespace: generic-device-labeller
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: generic-device-values
      valuesKey: "values.yaml"
    - kind: ConfigMap
      name: generic-device-values
      valuesKey: "plugin-config.yaml"
      targetPath: config.data
