#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/squat/generic-device-plugin
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag
  tag: latest

controller:
  # -- Sets the controller type
  type: daemonset

securityContext:
  # -- Privileged mode is required to access devices
  privileged: true

# -- Environment variables [[ref]](https://github.com/squat/generic-device-plugin#usage)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- The domain to use when declaring devices
  DOMAIN: squat.ai

persistence:
  # -- Host path volume bind to the Kubelet plugin directory
  # @default -- See [values.yaml](./values.yaml)
  device-plugins:
    enabled: true
    type: hostPath
    hostPath: /var/lib/kubelet/device-plugins
  # -- Host path volume bind to the dev dir
  # @default -- See [values.yaml](./values.yaml)
  dev:
    enabled: true
    type: hostPath
    hostPath: /dev

config:
  # -- Enables the config file ConfigMap
  enabled: true
  # -- generic-device-plugin config file [[ref]](https://github.com/squat/generic-device-plugin#usage)
  # @default -- See [values.yaml](./values.yaml)

service:
  # -- Configures health/metrics service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080

probes:
  # -- Configures liveness probe
  liveness:
    type: HTTP
    path: /health
  # -- Configures readiness probe
  readiness:
    type: HTTP
    path: /health
  # -- Configures startup probe
  startup:
    type: HTTP
    path: /health

serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: true
    # -- Configures the endpoints for the serviceMonitor.
    # @default -- See [values.yaml](./values.yaml)
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 30s
        scrapeTimeout: 10s
