#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/advplyr/audiobookshelf
  # -- image tag
  # @default -- chart.appVersion
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [audiobookshelf documentation](https://hub.docker.com/r/advplyr/audiobookshelf)
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/London
  AUDIOBOOKSHELF_UID: 1000
  AUDIOBOOKSHELF_GID: 1000

securityContext:
  runAsUser: 1000
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: "ingress-traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: audiobookshelf.thephysicsflat.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 80

    tls:
      - secretName: audiobookshelf-tls
        hosts:
          - "*.thephysicsflat.xyz"

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    type: nfs
    server: nfs.home.thephysicsflat.xyz
    path: /srv/media/configs/audiobookshelf/config
  metadata:
    enabled: true
    mountPath: /metadata
    type: nfs
    server: nfs.home.thephysicsflat.xyz
    path: /srv/media/configs/audiobookshelf/metadata
  media:
    enabled: true
    type: nfs
    mountPath: /audiobooks
    server: nfs.home.thephysicsflat.xyz
    path: /srv/media/Audiobooks
