apiVersion: v1
kind: Secret
metadata:
  name: config-secrets
  namespace: castsponsorskip
type: Opaque
stringData:
  youtube_api_key: ENC[AES256_GCM,data:0062L4AkRZu4icXIpOHwmTx2tAzN7swYgvCsEOE5bk0vkLviofZq,iv:kkTfKdn9T5FufzQLWi70ePnkpbcIMTLHjrLqoDAiNOw=,tag:DObznnVyTEg/w9p/eeQ7Qw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRk56US9mNzEwYVE0R3pX
        QnJCUDYxY0JWbG1VVXRDNXBHVkIzRXdGUUFBCkg4M2cvZXVTWHY1MU9CdkZFMWhs
        N0FDQXV5cERUMmFEWHZTR1lyaWU5eFkKLS0tIER0L0JERkJwdCsvS1k3WUhtbVNl
        V1pJWXVZSTI5N0JBWXVWVERsVmlHTHcKtq/DgkRSJe3UJ2s3JRRHyTE+YQ9ib9jD
        uiZqNrti+pEZgbi3Yh5HxP28eMV6ZuyF42OhaZj7r2KjQdHBJdWVwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-07T20:18:05Z"
  mac: ENC[AES256_GCM,data:Z1z1bpsMQkimeWU3h2i293ENf23gMjfkGk7SkeSzcGM9/70764kIP7iZDf08yd5ejrlsRPTLzy8vo7H2B23M/+IgcYWyFl62TK/l2Bp1UgIBREnOY5MuYy/+wFEghwV7p4Pw9vwigxNZeuSNCIOSLp7GbxJB6Q4B59on8lTJasU=,iv:NTsgpE7aYgLpB15CL/iOlMraqrTpirisaSzKwLLM/aw=,tag:I5Ztk+pIaCzcV11ZQQAJ6A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
