apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: castsponsorskip
configMapGenerator:
  - name: isponsorblocktv
    behavior: create
    files:
      - ./isponsorblocktv.json
    options:
      disableNameSuffixHash: true
resources:
  - castsponsorskip.yaml
