apiVersion: v1
kind: Secret
metadata:
  name: technitium-secrets
  namespace: technitium
type: Opaque
stringData:
  admin_password: ENC[AES256_GCM,data:kGzP/pjci22ekxsmN/CdEGT1l7YFJFgWVH/QZrn5k2FZxm2h457ui7EHtw==,iv:qGYxGG4NtXq6AYj/PokiYScKUgo0T+G9o78kdiIsewY=,tag:1Hzz0maYnrQ0dmXCngc/ag==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWWFmTDR3TUFjejJ3YWJS
        WFlGbnNvMmR0bVB1VHhHeU9ESFBCWXUrTkZzCm9WdGxKUTYyZkgrdEdZc3J5bFRD
        MHpzYUg2WEtNME8xdnluWis4NHErNXMKLS0tIEt2YS81a2s4SG9KUjd3R1Rxc0pP
        WGEvZjU2QmpMTHU1QzBnSWViTDBzbEUK5AUb+CbGd/IROdTabEkgvYDify7SQNKl
        nI+MxV8Je5FiPib2E+bpZ33qxvJj2rvLlZ5YhBoOKCkhjPhp+82xOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-15T22:04:42Z"
  mac: ENC[AES256_GCM,data:99czrUj0BxlIFXGQqyV2GhsfRWJa9ApLqWNrRAjvC0gAWy1pcCpE5pITf4VRv/h6HhAen+J5YbtIIYRixm/4M4pqjY0e5JYn+F/PZD8vMubKc+rc7AySltAKSLpYlDkK2BZcuo7Er8Ay3yHOgx+es9kCLDkttJvJsiXwXiNrW6A=,iv:j+MWYnY+RGBPuI+fZMX3iNM81MUI/CagtTQRc+ny1Ag=,tag:zjVybqfZ0gnmmeld+SGdcg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
