apiVersion: v1
kind: Secret
metadata:
  name: oidc-config
  namespace: oauth2-proxy
type: Opaque
data:
  cookie-secret: ENC[AES256_GCM,data:1WfRReaBHYLl1yxp/oO8NQ29K6sRQ0EoFyYsSsv+Wz93GIne+qCAtPJudys=,iv:fc4xxM14x3OZKBr7X7SPGzn60No+ZN5eQKHTBF4n5kc=,tag:WOCffx6icaMNcNyZp9LWkQ==,type:str]
  client-id: ENC[AES256_GCM,data:iM3H/9c/ICI3jmLHHyxMbFc/JOY0J5612STXGlz1NT0NLsXilwZqYy+K1U8vbC0j,iv:zr0fGGIkCzrazw5Z6fvW2+0eJNcd6Q3w78bGQsO7tpQ=,tag:oBh9vKnJvjc8W1gtysQA6w==,type:str]
  client-secret: ENC[AES256_GCM,data:rPP1xal9R8lR1z2NJ2czXCXI6UMDKhIjuMx3qYgsBKdfrhwowg+FskJOjsweUIJT2Lp7HIZuAzQ=,iv:c9XK07HfkY+AAOePITbma+jQvPxt5ePaVZz3SqfK32E=,tag:G8XqYPFV9L9KAFZ3kd2jXw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOTZBVHh4VDIxU3hTZ2xZ
        cFlNeTd1QTNJa3JRbU14QzdKNVVWekpXSWtZCktHN3NLOUw3cFlaeXhRbXhZRlN4
        MWUyU0NBblBxdHdxaTAvdHU1L3diY2MKLS0tIHhLVUliWU5nd2QvejA4QTJDSVNn
        WnJiTm9YZnN5K1FDa2lQOFB1dm1lYW8K87S5O783vbASWnNLOcXz2BxtmVsBYkfo
        1ZIannglcFXws3DD82OfGP5lH5E4ltLbNBEmjv6I+oy2jnqqi2KYXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-02-26T12:40:09Z"
  mac: ENC[AES256_GCM,data:X2ajqWRvZVOdU8FCAPJz9p2k6nls9ttCvj0stXY/rrhJ3JBHqLzrfTvCOwvUyXh+XQaYLu5avyOaCYvSagFQPgrfYy+J26tRfjY7tO79YFIURfCfPjqFxvfk/RTXi0ysA50Kntqmst3z9U8x4hiA/fRtAp8ODbbpxbQv+vHtPlE=,iv:PIpCVadJOjarywAA3uYNehD34jia48c0DbJEOr2qYgM=,tag:TLXXvdCbXafJNrhyeCPD9w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
