---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mumble-tls
  namespace: mumble
spec:
  secretName: mumble-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - mumble.thephysicsflat.xyz
