---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mumble
  namespace: mumble
spec:
  chart:
    spec:
      chart: mumble
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: syntaxerror404
  interval: 60m0s
  valuesFrom:
    - kind: ConfigMap
      name: mumble-values
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: mumble-server
              spec:
                template:
                  spec:
                    containers:
                      - name: mumble
                        env:
                          - name: MUMBLE_CONFIG_SERVER_PASSWORD
                            valueFrom:
                              secretKeyRef:
                                key: password
                                name: mumble-server-password
                        volumeMounts:
                          - name: tls
                            mountPath: /var/run/secrets/mumble-tls
                            readOnly: true
                    volumes:
                      - name: tls
                        secret:
                          secretName: mumble-tls
                          defaultMode: 0544
