apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-caddy
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-caddy
  template:
    metadata:
      labels:
        app: error-caddy
    spec:
      containers:
        - name: error-caddy
          image: caddy:alpine
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "100Ki"
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: caddy-data
              mountPath: /data
          ports:
            - containerPort: 80
              name: web
      volumes:
        - name: caddy-config
          configMap:
            name: constant-401-caddyfile
        - name: caddy-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: error-caddy
  namespace: jellyfin
spec:
  selector:
    app: error-caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
      name: web
