apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml
  - mail-secret.yaml
configMapGenerator:
  - name: ihatemoney-values
    namespace: ihatemoney
    files:
      - values.yaml
