#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ihatemoney/ihatemoney
  # -- image tag
  # @default -- chart.appVersion
  tag: master
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [ihatemoney documentation](https://hub.docker.com/r/advplyr/ihatemoney)
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/London
  SECRET_KEY:
    valueFrom:
      secretKeyRef:
        name: ihatemoney-secrets
        key: secret-key
  MAIL_SERVER: smtppro.zoho.eu
  MAIL_USERNAME:
    valueFrom:
      secretKeyRef:
        name: ihatemoney-secrets
        key: mail-username

  MAIL_DEFAULT_SENDER:
    valueFrom:
      secretKeyRef:
        name: ihatemoney-secrets
        key: mail-username
  MAIL_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: ihatemoney-secrets
        key: mail-password
  ADMIN_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: ihatemoney-secrets
        key: admin-password
  ACTIVATE_DEMO_PROJECT: "False"
  MAIL_PORT: 465
  MAIL_USE_SSL: "True"
  ACTIVATE_ADMIN_DASHBOARD: "True"
  # ADMIN_PASSWORD:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      # traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: ihatemoney.thephysicsflat.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8000

    tls:
      - secretName: ihatemoney-tls
        hosts:
          - "*.thephysicsflat.xyz"

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  database:
    enabled: true
    mountPath: /database
    type: pvc
    retain: true
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 512Mi
