apiVersion: v1
kind: Namespace
metadata:
  name: amd-gpu
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: amd-gpu
  namespace: amd-gpu
spec:
  interval: 24h
  url: https://rocm.github.io/k8s-device-plugin/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: amd-gpu
spec:
  interval: 30m
  chart:
    spec:
      chart: amd-gpu
      sourceRef:
        kind: HelmRepository
        name: amd-gpu
        namespace: amd-gpu
      interval: 12h
  values:
    labeller:
      enabled: true
    nfd:
      enabled: true
