apiVersion: v1
kind: Namespace
metadata:
  name: amd-gpu
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: amd-gpu
  namespace: amd-gpu
spec:
  interval: 24h
  url: https://rocm.github.io/k8s-device-plugin/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: amd-gpu
spec:
  interval: 30m
  chart:
    spec:
      chart: amd-gpu
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu
        namespace: amd-gpu
      interval: 12h
  values:
    nfd:
      enabled: true

    labeller:
      enabled: true

    dp:
      image:
        repository: docker.io/rocm/k8s-device-plugin
      resources: {}

    lbl:
      image:
        repository: docker.io/rocm/k8s-device-plugin
      serviceAccount:
        annotations: {}
      securityContext:
        privileged: true # Needed for /dev
        capabilities:
          drop:
            - ALL
          add:
            - CAP_SYS_ADMIN
        readOnlyRootFilesystem: false # true if -logtostderr flag set in labeller
      # If you do want to specify resources, uncomment the following lines,
      # adjust them as necessary, and remove the curly braces after 'resources:'.
      resources:
        {}
        # limits:
        #   memory: 20Mi
        #   cpu: 100m
        # requests:
        #   memory: 30Mi
        #   cpu: 150m

    imagePullSecrets: []

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

    node_selector_enabled: true
    node_selector:
      feature.node.kubernetes.io/pci-0300_1002.present: "true"
      kubernetes.io/arch: amd64
