apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
configMapGenerator:
  - name: metallb-helm-chart-value-overrides
    files:
      - values.yaml

resources:
  - metallb.yaml
