apiVersion: v1
stringData:
    api-token: ENC[AES256_GCM,data:WUBXNM6sQ/MYW5wKHx2RqK7fbIME8k9muUPP/ZQwOXr1NoUfwZMybOt3ln9z4/6tmqLDGOQ=,iv:emmfqX/lhhOHvSDr+ZV/kDmFknhaAuEF8qab8F50JXQ=,tag:A9XH8pvA9e2zcvm1V8hN8g==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcDNOTEl0eUtYQVRUUjU2
            cXhZUlVpcEt3YnlXRHVBNm5nT3hXWDdybUg4ClVzZkZ6WUtCYU1LV1ZITm1idEtk
            c3NObjA3WExITDFpc2xCdUNyVXZ0OVEKLS0tIEFPQ3hhM21Zbzd6VUtUS2EzaDg3
            dnpsQUdFVnZKMFd1VU8rTWJOUGFvSzgKzH6K5kgInKZ/vzXWkipidl4bkjrH60eA
            nA2lEiNBP9JhgGpqu5F9T88Tw4qGh3uOC8YGLwAD4uCdvKj2g5hvFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T16:46:38Z"
    mac: ENC[AES256_GCM,data:zRebcNL2rzcYcrDvP98zDYNYLTRTAAJ0sIy5Vqbc5mv+u/G5w/83rDWRjQij90CTUsOvXlxFTr3aAN/UtKeVBQ36HLnVtFPSf3CQLDuCMfSpqcGW7T4eu4odpQpfFa8r7pN2InJMiTzS/uiV8qVZxkv2GdL1UnjBEXAW09FGFzM=,iv:ObvcGAFCFtoPZSiMqcFn5aFIeknHtyDRiaqSzMcMtAo=,tag:9eUfE3MNinbMsRZtIDit1A==,type:str]
    version: 3.13.3
