apiVersion: v1
data:
    key: ENC[AES256_GCM,data:N+LuPbF4NrDhc4qMmpbSN+m+9NR3xhyhwWuLlKXA+f1ynHndCkBMMJdXUhxoyV959ragEBrxV0TU4w==,iv:JX+dwETn/efr6LVyRHjI49nXJMFSxIo0mR61Hrhmcks=,tag:+oEtpMl445ulMOJwvfTgew==,type:str]
kind: Secret
metadata:
    name: netlify-pat
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcDNOTEl0eUtYQVRUUjU2
            cXhZUlVpcEt3YnlXRHVBNm5nT3hXWDdybUg4ClVzZkZ6WUtCYU1LV1ZITm1idEtk
            c3NObjA3WExITDFpc2xCdUNyVXZ0OVEKLS0tIEFPQ3hhM21Zbzd6VUtUS2EzaDg3
            dnpsQUdFVnZKMFd1VU8rTWJOUGFvSzgKzH6K5kgInKZ/vzXWkipidl4bkjrH60eA
            nA2lEiNBP9JhgGpqu5F9T88Tw4qGh3uOC8YGLwAD4uCdvKj2g5hvFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T22:33:40Z"
    mac: ENC[AES256_GCM,data:kitWMnkl+gzv6sEY7ZnDQnfwa8w1JZM9i6MaXpf6ZDM92uyV5CP3QhbQEDkK+0sX5G9pHgvrIoYmrwBuToi5RIDLd75N+rLmHcuXuSXM1ZZAoUfO+OQvP7FV9hyH2a5HnnM7LTL7ic9dvrCKJBhxUv/2wR4Lz6Vn5/KlXjF3XSE=,iv:JbkZEIMGo2tiKLn68t3aE2ykNTGiHt5wX++tTELbB9E=,tag:R22x0d6Se9CYmnJARcyujA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
