apiVersion: v1
data:
    key: ENC[AES256_GCM,data:Dr4S6kWsz5/x5FNn6cklC5y2okNsf8pkrk1EfLAwDGcJ3wT4BtAdR8OvPJLheaFR8Hzh9xj70fKN8ole,iv:bfQG5wA2JIzT7QVvVDNNqBBA0dbA1inH42sMmuvUNtE=,tag:p5ClAtPrOXBfSJq+z85sHA==,type:str]
kind: Secret
metadata:
    name: netlify-pat
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcDNOTEl0eUtYQVRUUjU2
            cXhZUlVpcEt3YnlXRHVBNm5nT3hXWDdybUg4ClVzZkZ6WUtCYU1LV1ZITm1idEtk
            c3NObjA3WExITDFpc2xCdUNyVXZ0OVEKLS0tIEFPQ3hhM21Zbzd6VUtUS2EzaDg3
            dnpsQUdFVnZKMFd1VU8rTWJOUGFvSzgKzH6K5kgInKZ/vzXWkipidl4bkjrH60eA
            nA2lEiNBP9JhgGpqu5F9T88Tw4qGh3uOC8YGLwAD4uCdvKj2g5hvFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T22:58:09Z"
    mac: ENC[AES256_GCM,data:f8e8bHjmKBCoBm624toFOWjnxigDhFgXIVAAUypx0CpDe2AWn6ieDs7qMsnefTB9Rnij9/f9DMYh5y9GYckVM1Df+ZGIXFwiZ0kw6teIy9WIZF3D7zVCrk3q7um94Nd7/3vMvwIIwx5690BtcYXhbMH5HNDHDr4P/1+qv4p7Jh8=,iv:e0+LTgM0qjs9PU2oPzqUb8v3wFFW2nmDmS9FBRyjFyI=,tag:RydBoi+HfSR6TWUBlukOow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
