apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  chart:
    spec:
      chart: paperless
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: default
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: paperless-values
