apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  chart:
    spec:
      chart: paperless
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: default
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: paperless-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keydb
  namespace: paperless
spec:
  chart:
    spec:
      chart: keydb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: default
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: redis-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gotenberg
  namespace: paperless
spec:
  chart:
    spec:
      chart: gotenberg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: maikumori
        namespace: default
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: gotenberg-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tika
  namespace: paperless
spec:
  chart:
    spec:
      chart: tika
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tika
        namespace: default
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: tika-values
