apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subgen-models
  namespace: jellyfin
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
