apiVersion: v1
kind: Secret
metadata:
  name: pihole-password
  namespace: external-dns-system
stringData:
  pihole-password: ENC[AES256_GCM,data:tLQtcmlwXqA=,iv:9jux3EIVpnjlH1NBtN/Pd9aNhVNaPDMxZi5B4qmm3f0=,tag:6PcN92MjCWz0oN6sDL7gEw==,type:str]
sops:
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OGZmYnFjZWRKblJuT2c5
        clFQd2tpMW9tOU16eTlGRzBIRm91aDhTdWhnCkNsM0JQcUFiVVZLSzFsVzNqUi9O
        VlhKVzJwY1hYbjhjZ1FIVnJJTGpiZ3cKLS0tIHVpYWNFbUhNaHhYejlXS1o3bzRh
        eEhyZm5sQ2xSUEFQZExRbXZDdjlFMmsKHPCH9RCpcTx/eKXTSVJV/jCu+RUcATJU
        N87SNSrTLfA+LJshUWRSmG2XLiCKIliujHADJ2CJOcEqKv6rHGmVPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-05T15:53:05Z"
  mac: ENC[AES256_GCM,data:kqxpIXVSxase9TQ+QAb/NNY1pT/xV3RBWQOIydfmPdE0JvTWmp+IfvV/hRApKfKbMxp5WdDVsNeu90lQUAxtylNHrRy7iRPynzYr6yKTfmlAoQFWkJLo28qy9XXcFLQYcmXvaPTxQnc06/F3di/VeDK3CsbvyaJyFSS/HYHW1Ac=,iv:hzz+w5IbzGpUaPWFLBrEmL5XAHhou0KI95FMkmteHCs=,tag:CETQLfuRvaWNLJ9j5K9bzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
