apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/external-dns
