apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pihole-cors
  namespace: pihole
spec:
  headers:
    accessControlAllowOriginList: ["*"]
    accessControlAllowMethods: ["GET", "OPTIONS", "PUT", "POST", "DELETE"]
    accessControlAllowHeaders:
      - Origin
      - X-Requested-With
      - Content-Type
      - Accept
      - Authorization
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true
