apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
  interval: 60m0s
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values
