apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/proxy-class: default
    tailscale.com/hostname: pihole
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
    release: pihole
  name: pihole-dns-ts
  namespace: pihole
spec:
  ports:
    - name: dns
      port: 53
      protocol: TCP
      targetPort: dns
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app: pihole
    release: pihole
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerClass: tailscale
