title: "Local Services"
subtitle: "Across Kubernetes"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: auto

# Optional theme customization
theme: default

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "External"
    icon: "fas fa-cloud"
    items:
      - name: Audiobookshelf
        url: https://audiobookshelf.thephysicsflat.xyz
      - name: Home Assistant
        url: https://home.thephysicsflat.xyz
      - name: Calibre-Web
        url: https://calibre-web.thephysicsflat.xyz
      - name: Vaultwarden
        url: https://vaultwarden.thephysicsflat.xyz
  - name: "Internal"
    icon: "fas fa-network-wired"
    items:
      - name: ihatemoney
        url: https://ihatemoney.thephysicsflat.xyz
      - name: PiHole
        url: https://pihole.x86.thephysicsflat.xyz/admin/
        type: PiHole
      - name: Paperless
        url: https://paperless.x86.thephysicsflat.xyz
#   - name: "System"
#     icon: "fas fa-gear"
#     items:
#       - name: Kubernetes Dashboard
#         url: https://kubernetes-dashboard.home.thephysicsflat.xyz
#       - name: Weave
#         url: https://weave.home.thephysicsflat.xyz
#
