apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: homer-values
    namespace: homer
    files:
      - values.yaml
      - homer-config.yaml
