apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homer
  namespace: homer
spec:
  releaseName: homer
  chart:
    spec:
      chart: homer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: default
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: homer-values
