#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: b4bz/homer
  # -- image tag
  tag: v24.04.1
  # -- image pull policy
  pullPolicy: IfNotPresent

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- environment variables.
# @default -- See [values.yaml](./values.yaml)
env:
  TZ: Europe/London
  # INIT_ASSETS: "0"

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: homer.home.thephysicsflat.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8080

    tls:
      - secretName: homer-tls
        hosts:
          - "homer.home.thephysicsflat.xyz"

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  config:
    enabled: true
    type: configMap
    mountPath: /www/assets/config.yml
    subPath: homer-config.yaml
    name: config
