apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: webhook-netlify-dns
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: webhook-netlify-dns
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: webhook-netlify-dns
        namespace: cert-manager
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: webhook-values
      valuesKey: values.yaml
