apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: webhook-netlify-dns
  namespace: cert-manager
spec:
  interval: 24h
  url: https://penguinoneshaw.github.io/webhook-netlify-dns
