apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: home-assistant
spec:
  image: emqx:5
  coreTemplate:
    spec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "125m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      volumeClaimTemplates:
        storageClassName: longhorn
        resources:
          limits:
            storage: 300Mi
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce
      replicas: 3
  listenersServiceTemplate:
    enabled: true
    spec:
      type: LoadBalancer
      loadBalancerIP: "10.1.11.3"
    metadata:
      annotations:
        metallb.io/allow-shared-ip: home-assistant
  dashboardServiceTemplate:
    enabled: true
    spec:
      type: LoadBalancer
      loadBalancerIP: "10.1.11.3"
    metadata:
      annotations:
        metallb.io/allow-shared-ip: home-assistant
