apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: home-assistant
spec:
  image: emqx:5
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: longhorn
        resources:
          requests:
            storage: 20Mi
        accessModes:
          - ReadWriteOnce
      replicas: 3
  listenersServiceTemplate:
    enabled: true
    spec:
      type: LoadBalancer
      loadBalancerIP: "10.1.11.3"
    metadata:
      annotations:
        metallb.io/allow-shared-ip: home-assistant
  dashboardServiceTemplate:
    enabled: true
    spec:
      type: LoadBalancer
      loadBalancerIP: "10.1.11.3"
    metadata:
      annotations:
        metallb.io/allow-shared-ip: home-assistant
