apiVersion: v1
kind: Secret
metadata:
    name: rtl433-config
type: Opaque
data:
    PASSWORD: ENC[AES256_GCM,data:pGgg7VE3tva+4bdk7sdTbQ==,iv:ESYy1TKcxYmsgH+3C+45jF6ssoB15HjP9UCBl8CxNx4=,tag:RuCfHAFcrJPH88KGrVjclA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcUI0Y05mVVpyVU51OHEx
            SVhCczFZZXhpdzBpTjVmald1eXB3Ry8zNnlZCmlqalVreUh3Y1NuS1pNcTZLcTFO
            N29ydUZ0TzV0K2ZPSXQ5VWIzeFNCNXMKLS0tIFpqRTFCZ1FYN1BtQVBXZ1JYMFJW
            OTQzblBmd1RFN3FNUkZKdkZPclpkQlkKMWsyq9kBQsOVp0RPBxeeuuXjxoMtpczJ
            gcyp6SFnUb2rWn1k+bY+M9WEthjQXA4LRieBv+qoqw3X945+FtEhZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T14:51:53Z"
    mac: ENC[AES256_GCM,data:2irdIjCUUA6WL6SQjZWSsPZnvN1iCWL/qlBowBICydTwSX+bt9A5FZBKPRMfW0fTXxelxjz9ueTxyEfuwuw37fgODxO9N0Hn1p8yGj1PVD/6F6U7rAEPrdCDPK/NmaVFkb+Z2IJDSLTbfumMo743he6hWvWmL+TkVkF+BQgeTQQ=,iv:TNsbDoMK1IsyyZG/w54R3ratgxU7EcnZJHPVZMJPlKM=,tag:Wo5osphiMti80wyT/95Vuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
