apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: ExternalName
  externalName: james-raspi4
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
