apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner-system

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs
  namespace: nfs-provisioner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: default
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: nfs-provisioner-values
      valuesKey: values.yaml
