apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: matrix
  namespace: flux-system
spec:
  providerRef:
    name: matrix
  eventSources:
    - kind: HelmRelease
      name: "*"
    - kind: Kustomization
      name: "*"
