apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: matrix
  namespace: flux-system
spec:
  type: matrix
  address: https://matrix.org
  channel: "!RJvIAcMllAMRVDZlUP:matrix.org"
  secretRef:
    name: matrix-token
