apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-middleware
  namespace: jellyfin
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      X-XSS-PROTECTION: "0"
    stsSeconds: 315360000
    stsIncludeSubdomains: true
    frameDeny: true
    contentTypeNosniff: true
