---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: djjudas21
        namespace: jellyfin
  targetNamespace: jellyfin
  interval: 60m0s
  upgrade:
    remediation:
      strategy: rollback
      retries: 10
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-values
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.home.thephysicsflat.xyz
    path: "/srv/media"
    readOnly: false
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-books
  namespace: jellyfin
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  nfs:
    server: nfs.home.thephysicsflat.xyz
    path: "/srv/books/Books"
    readOnly: false
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 512Gi
  volumeName: jellyfin-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-books
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 64Gi
  volumeName: jellyfin-books
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  podMetricsEndpoints:
    - port: web
      path: "/metrics"
  selector:
    matchLabels:
      app.kubernetes.io/name: "jellyfin"
      app.kubernetes.io/instance: "jellyfin-jellyfin"
