---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir
        namespace: jellyfin
  interval: 60m0s
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-values
