# -- Number of replicas to run. Chart is not designed to scale horizontally, use at your own risk
replicaCount: 1

# -- Use host network
hostNetwork: false

port: 8096
hostPort:
  # -- Use host port for the application
  enabled: false
  # -- Host port to bind to
  port: 8096

# -- Additional port definitions for the pod
additionalPorts:
  []
  # - name: tcp-8920
  #   containerPort: 8920
  #   protocol: TCP
  #   hostPort: 8920
  # - name: udp-1900
  #   containerPort: 1900
  #   protocol: UDP
  #   hostPort: 1900
  # - name: udp-7359
  #   containerPort: 7359
  #   protocol: UDP
  #   hostPort: 7359

# -- Additional port definitions for the service
additionalServicePorts: []

image:
  # -- Image repository
  repository: docker.io/linuxserver/jellyfin
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag (if not specified, defaults to the chart's appVersion)
  tag: "10.10.0"

# -- Image pull secrets
imagePullSecrets: []
# -- String to partially override fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override fullname template with a string
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for the pods
podAnnotations: {}

# -- Security context for the pods
podSecurityContext: {}

# -- Security context for the container. NET_ADMIN capability is required for the VPN to work properly.
securityContext:
  capabilities:
    add:
      - NET_ADMIN

# -- Deployment strategy
strategy:
  type: Recreate

service:
  # -- Type of the service
  type: ClusterIP
  # -- Port for the service to use
  port: 8096

ingress:
  # -- Expose the app using an ingress
  enabled: true
  # -- Ingress class name
  className: nginx
  # -- Annotations for the ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffering: "on"

  # -- Ingress hosts configuration
  # @default -- see [values.yaml](values.yaml)
  hosts:
    - host: jellyfin.thephysicsflat.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- The TLS configuration for the Ingress
  tls:
    - secretName: jellyfin-tls
      hosts:
        - "jellyfin.thephysicsflat.xyz"

# -- The resource requests and limits of the container
resources:
  amd.com/gpu: 1

# -- The node selector for the deployment
nodeSelector: {}

# -- Tolerations for the pod assignment
tolerations: []

# -- Affinity for the pod assignment
affinity: {}

persistence:
  config:
    # -- Config: Enable persistence
    enabled: true
    # -- Config: Persistence type is pvc. When `false`, data volume definition is read from `persistence.config.customVolume`
    isPvc: true
    # -- Config: Name of the existing claim to be used for config
    existingClaim: ""
    # -- Config: Storage class for the volume
    storageClass: "nfs-client"
    # -- Config: Annotations for the claim
    annotations:
      helm.sh/resource-policy: keep
    # -- Config: Access modes for the claim
    accessModes:
      - ReadWriteOnce
    # -- Config: Size for the claim
    size: 2Gi
    # -- Config: Alternative data volume definition (e.g. nfs, hostPath). Used when `persistence.config.isPvc` is `false`
    customVolume:
      {}
      # hostPath:
      #   path: /path/on/host
  data:
    # -- Data: Enable persistence
    enabled: true
    # -- Data: Persistence type is pvc. When `false`, data volume definition is read from `persistence.data.customVolume`
    isPvc: false
    # -- Data: Name of the existing claim to be used
    existingClaim: ""
    # -- Data: Storage class for the data volume
    storageClass: ""
    # -- Data: Annotations for the claim
    annotations: {}
    # helm.sh/resource-policy: keep
    # -- Data: Access modes for the claim
    accessModes:
      - ReadWriteOnce
    # -- Data: Size for the claim
    size: 64Gi
    # -- Data: Alternative data volume definition (e.g. nfs, hostPath). Used when `persistence.data.isPvc` is `false`
    customVolume:
      nfs:
        server: nfs.home.thephysicsflat.xyz
        path: /srv/media

# -- Non-sensitive environment variables to be set in the pods. See the [application docs](https://docs.linuxserver.io/images/docker-jellyfin)
env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
  JELLYFIN_PublishedServerUrl: "https://jellyfin.thephysicsflat.xyz"
# -- Sensitive environment variables to be set in the pods. See the [application docs](https://docs.linuxserver.io/images/docker-jellyfin)
secretEnv: {}

# -- DNS configuration for the pod
dnsConfig: {}

# -- DNS policy for the pod
dnsPolicy: ClusterFirst

# -- Arbitrary extra volume definitions for the pod
extraVolumes:
  - name: books
    nfs:
      server: nfs.home.thephysicsflat.xyz
      path: /srv/books/Books
      readonly: true

# -- Arbitrary extra volume mounts for the pod
extraVolumeMounts:
  - name: books
    mountPath: /data/books

# -- Pod liveness probe
livenessProbe: {}

# -- Pod readiness probe
readinessProbe:
  httpGet:
    port: http

# -- Init containers
initContainers:
  []
  # - name: init
  #   image: busybox:stable-musl
  #   command:
  #     - sh
  #     - -c
  #     - echo "initializing..."

# -- Sidecar containers
sidecarContainers:
  []
  # - name: sidecar
  #   image: busybox:stable-musl
  #   command:
  #     - tail
  #     - -f
  #     - /dev/null
