apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copyparty
  namespace: copyparty
spec:
  interval: 5m
  chart:
    spec:
      chart: copyparty
      sourceRef:
        kind: HelmRepository
        name: copyparty
  valuesFrom:
    - kind: ConfigMap
      name: copyparty-values
