apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  # At the time of writing, immich is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.4.2
  instances: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  affinity:
    nodeSelector:
      kubernetes.io/arch: amd64
  managed:
    roles:
      - name: immich
        login: true
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;

  storage:
    size: 4Gi
    storageClass: nfs-client
