apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: immich
spec:
  resources:
    requests:
      storage: 250G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
