apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      version: "0.8.4"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: immich-values
    - kind: Secret
      name: oauth-secret
      targetPath: immich.configuration.oauth.clientSecret
      valuesKey: clientSecret
