apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanidm-ingress-tls
  namespace: kanidm
spec:
  secretName: kanidm-ingress-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: idm.thephysicsflat.xyz
  dnsNames:
    - idm.thephysicsflat.xyz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanidm
  namespace: kanidm
  labels:
    app.kubernetes.io/name: kanidm
    app.kubernetes.io/instance: kanidm-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: kanidm
  serviceName: kanidm
  replicas: 1
  template:
    metadata:
      labels:
        app: kanidm
    spec:
      containers:
        - name: kanidm
          image: docker.io/kanidm/server:1.8.5
          args: ["kanidmd", "server", "-c", "/config/server.toml"]
          securityContext:
            allowPrivilegeEscalation: false
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              port: https
              path: /status
              scheme: HTTPS
          readinessProbe:
            httpGet:
              port: https
              path: /status
              scheme: HTTPS
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
            - name: tls
              mountPath: /tls
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 300Mi
              cpu: 250m
          ports:
            - name: https
              containerPort: 8443
            - name: ldap
              containerPort: 3636

      volumes:
        - name: config
          configMap:
            name: kanidm
            defaultMode: 0660
        - name: tls
          secret:
            secretName: kanidm-ingress-tls
            defaultMode: 0660
        - name: data
          persistentVolumeClaim:
            claimName: kanidm-data

      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1100
        runAsGroup: 1100
        fsGroup: 1100
        fsGroupChangePolicy: "OnRootMismatch"
        readOnlyRootFilesystem: true

---
apiVersion: v1
kind: Service
metadata:
  name: kanidm
  labels:
    app: kanidm
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  type: ClusterIP
  selector:
    app: kanidm
  ports:
    - name: https
      port: 8443
      targetPort: https
    - name: ldaps
      port: 3636
      targetPort: ldap
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kanidm
  namespace: kanidm
spec:
  tls:
    passthrough: true
    domains:
      - main: "idm.thephysicsflat.xyz"
    secretName: kanidm-ingress-tls
  routes:
    - match: "HostSNI(`idm.thephysicsflat.xyz`)"
      services:
        - name: kanidm
          namespace: kanidm
          port: https

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiusd
  namespace: kanidm
  labels:
    app.kubernetes.io/name: kanidm
    app.kubernetes.io/instance: kanidm-radiusd
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: radiusd
  template:
    metadata:
      labels:
        app: radiusd
    spec:
      containers:
        - name: radiusd
          image: docker.io/kanidm/radius:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 1812
              protocol: TCP
              name: auth-tcp
            - containerPort: 1812
              protocol: UDP
              name: auth-udp
            - containerPort: 1813
              protocol: TCP
              name: accounting-tcp
            - containerPort: 1813
              protocol: UDP
              name: accounting-udp

          volumeMounts:
            - name: radiusd-server-tls
              mountPath: /data/cert.pem
              subPath: tls.crt
              readOnly: true
            - name: radiusd-server-tls
              mountPath: /data/key.pem
              subPath: tls.key
              readOnly: true
            - name: radiusd-ca
              mountPath: /data/ca.pem
              subPath: tls.crt
              readOnly: true
            - name: radiusd-config
              mountPath: /data/radius.toml
              subPath: radiusd.toml
              readOnly: true
      volumes:
        - name: radiusd-server-tls
          secret:
            secretName: radiusd-server-tls
        - name: radiusd-ca
          secret:
            secretName: radiusd-ca
        - name: radiusd-config
          secret:
            secretName: radiusd-config
            items:
              - key: radiusd.toml
                path: radiusd.toml

---
apiVersion: v1
kind: Service
metadata:
  name: radiusd
spec:
  selector:
    app: radiusd
  type: LoadBalancer
  loadBalancerIP: 10.1.11.4
  externalTrafficPolicy: Local
  ports:
    - port: 1812
      targetPort: auth-tcp
      protocol: TCP
      name: radius-tcp
    - port: 1812
      protocol: UDP
      targetPort: auth-udp
      name: radius-udp
    - port: 1813
      protocol: TCP
      name: accounting-tcp
    - port: 1813
      protocol: UDP
      name: accounting-udp
